/**
 * Difficulty tier of a LeetCode problem. Values match the exact strings
 * stored in the committed `data/` JSON files, so parsed archives type-check
 * without migration.
 */
export enum Difficulty {
  Easy = "Easy",
  Medium = "Medium",
  Hard = "Hard",
}

/**
 * Outcome of a submitted solution. Values match the exact strings stored in
 * the committed `data/` JSON files, so parsed archives type-check without
 * migration.
 */
export enum SolutionStatus {
  Done = "DONE",
  TimeLimitExceeded = "TLE",
  MemoryLimitExceeded = "MLE",
  Failed = "FAILED",
  FailedConstraints = "FAILED_CONSTRAINTS",
}

/** One day's LeetCode daily challenge, as stored in `data/problems`. */
export interface Problem {
  title: string;
  difficulty: Difficulty;
  /** Sanitized HTML of the problem statement. */
  description: string;
  /** Absolute URL of the problem on leetcode.com. */
  link: string;
  /** The challenge's UTC day, as `YYYY-MM-DD`. */
  date: string;
}

/** One submitted solution, as stored in `data/solutions`. */
export interface Solution {
  author: string;
  code: string;
  language: string;
  /** Markdown explanation generated by the `/explain` command. */
  aiExplanation?: string;
  /** Hand-written markdown notes. */
  notes?: string;
  status?: SolutionStatus;
  /** Runtime percentile, 0-100. */
  cpuUsage?: number;
  /** Memory percentile, 0-100. */
  memoryUsage?: number;
  /** Submission timestamp as an ISO string. */
  date: string;
}
